In [4]:
import numpy as np
# 1.
# a. 
print(np.arange(1, 11))
# b. 
print(np.arange(0.5, 5, 0.25, dtype=float))

[ 1  2  3  4  5  6  7  8  9 10]
[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75]


In [14]:
# 2.
# a. 
print(np.zeros(10))
# b. 
print(np.zeros((3, 4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
# 3. 
# a. 
print(np.linspace(2, 12, 5))
# b. 
print(np.linspace(3, 9, 4))

[ 2.   4.5  7.   9.5 12. ]
[3. 5. 7. 9.]


In [188]:
# 4. 
# a. 
rands = np.random.rand(4, 2)
print(rands)
# b. 
print(np.random.randint(10, 21, (3, 3)))
# reshape
print(np.reshape(rands, (1, 8))) # need to confirm that the amount of elements similar to the reshape elements given

[[0.02649575 0.24933312]
 [0.96852745 0.15075079]
 [0.3173104  0.46038184]
 [0.73552132 0.57229125]]
[[15 16 19]
 [19 16 20]
 [17 17 16]]
[[0.02649575 0.24933312 0.96852745 0.15075079 0.3173104  0.46038184
  0.73552132 0.57229125]]


In [ ]:
# 5. 
# We will get the same random of numbers by that given seed
# Seed using is good for making tests with different machins because that given seed does not change