In [4]:
import numpy as np

In [12]:
# 1. 
array01 = np.arange(1, 17)
np.reshape(array01, (4, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
# 2. 
array02 = np.arange(10, 50, 5)
np.reshape(array02, (2, 4))

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [34]:
# 3. 
array_rand = np.random.randint(1, 100, (3, 3))
print('Array:\n', array_rand)
print('Max value:\n', np.max(array_rand))
print('Min value:\n', np.min(array_rand))

Array:
 [[32 60 48]
 [57 62 69]
 [94  2 48]]
Max value:
 94
Min value:
 2


In [52]:
# 4. 
array03 = np.random.randint(0, 20, 10)
display(array03)
print('First 5 elements:\n', array03[:5])
print('All elements, jumps by 2:\n', array03[::2])
print('Reversed array:\n', array03[::-1])

array([ 7, 14,  4,  2,  7,  6,  0, 10,  1,  8], dtype=int32)

First 5 elements:
 [ 7 14  4  2  7]
All elements, jumps by 2:
 [7 4 7 0 1]
Reversed array:
 [ 8  1 10  0  6  7  2  4 14  7]


In [80]:
# 5. 
array04 = np.random.randint(1, 50, (4, 5))
display(array04)
print('Second row:\n', array04[1])
print('Fourth column:\n', array04[::, 3])

array([[12, 10, 24, 15, 16],
       [41, 36, 28, 19, 29],
       [16, 37, 11,  2, 24],
       [20, 23, 43, 22, 11]], dtype=int32)

Second row:
 [41 36 28 19 29]
Fourth column:
 [15 19  2 22]


In [102]:
# 6. 
array05 = np.random.randint(0, 100, 15)
display(array05)
print('Max value index:\n', np.argmax(array05))
print('Min value index:\n', np.argmin(array05))

# 6. Continue
array05_copy = np.copy(array05)
display(array05_copy)
print('Divided by 5:\n', array05_copy[array05_copy % 5 == 0])
print('Lower then 10 and higher then 50:\n', array05_copy[(array05_copy > 50) | (array05_copy < 10)])

array([32,  9, 24, 37, 88, 13, 21, 48, 19, 73, 44, 72, 36, 52, 31],
      dtype=int32)

Max value index:
 4
Min value index:
 1


array([32,  9, 24, 37, 88, 13, 21, 48, 19, 73, 44, 72, 36, 52, 31],
      dtype=int32)

Divided by 5:
 []
Lower then 10 and higher then 50:
 [ 9 88 73 72 52]


In [122]:
# Bonus. Didn't finish, let me know if I was on the diraction
seed_num_result = None
count = None
seed_num = 10
while seed_num <= 100:
    np.random.seed(seed_num)
    array_rand = np.random.ranf(15)
    display(array_rand)
    result = array_rand[array_rand > 80]
    result_len = len(result)
    if result_len > count or count == None:
        seed_num_result = seed_num
        count = result_len

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096])

TypeError: '>' not supported between instances of 'int' and 'NoneType'